// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYsklEXh8FvrcDuxX1c6GzwKz3SmSZuo4',
    appId: '1:810797163247:web:679ba991ce9e6c840b311a',
    messagingSenderId: '810797163247',
    projectId: 'chess-game-6b5b8',
    authDomain: 'chess-game-6b5b8.firebaseapp.com',
    storageBucket: 'chess-game-6b5b8.appspot.com',
    measurementId: 'G-R8KT1X0Y20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcrP225v_gwa9WB9j1PIqZjO8jSBO3dP8',
    appId: '1:810797163247:android:89345724e57051ab0b311a',
    messagingSenderId: '810797163247',
    projectId: 'chess-game-6b5b8',
    storageBucket: 'chess-game-6b5b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxpwEkPP1UsCeqytNrt4RLIdBB52HQHA4',
    appId: '1:810797163247:ios:b122e9910db94fa70b311a',
    messagingSenderId: '810797163247',
    projectId: 'chess-game-6b5b8',
    storageBucket: 'chess-game-6b5b8.appspot.com',
    androidClientId: '810797163247-hsphgdsqh749uf36114n2c3sm0dr1sbl.apps.googleusercontent.com',
    iosClientId: '810797163247-mvcfe3ioqfhktqs0nf9oi8anubm59smk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chessGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxpwEkPP1UsCeqytNrt4RLIdBB52HQHA4',
    appId: '1:810797163247:ios:8652dafd5456df3a0b311a',
    messagingSenderId: '810797163247',
    projectId: 'chess-game-6b5b8',
    storageBucket: 'chess-game-6b5b8.appspot.com',
    androidClientId: '810797163247-hsphgdsqh749uf36114n2c3sm0dr1sbl.apps.googleusercontent.com',
    iosClientId: '810797163247-vh6g7069tisnttavvhlmt8cgnfggckj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chessGame.RunnerTests',
  );
}
